CREATE TABLE MotivosCita
(
	TipoDoctor INT,
	MotivoCita VARCHAR(255)
)
INSERT INTO MotivosCita VALUES (1, 'Consulta de Anestesia');
INSERT INTO MotivosCita VALUES (2, 'Infarto');
INSERT INTO MotivosCita VALUES (3, 'Paño');
INSERT INTO MotivosCita VALUES (4, 'Diabetes');
INSERT INTO MotivosCita VALUES (5, 'úlcera gástrica');
INSERT INTO MotivosCita VALUES (6, 'Cirugía general');
INSERT INTO MotivosCita VALUES (7, 'cáncer en la sangre');
INSERT INTO MotivosCita VALUES (8, 'control de las defensas');
INSERT INTO MotivosCita VALUES (9, 'infecciones a largo plazo o que se repiten del riñón incluyendo la cistitis');
INSERT INTO MotivosCita VALUES (10, 'Migrañas');
INSERT INTO MotivosCita VALUES (11, 'Papanicolau');
INSERT INTO MotivosCita VALUES (12, 'extirpación de tejido enfermo');
INSERT INTO MotivosCita VALUES (13, 'Revision general');
INSERT INTO MotivosCita VALUES (15, 'al hablar por teléfono se escucha mejor de un lado del oído que del otro.');
INSERT INTO MotivosCita VALUES (16, 'problemas de postura');
INSERT INTO MotivosCita VALUES (17, 'Ataques de panico intensos');
INSERT INTO MotivosCita VALUES (18, 'Tos con resequedad y dolor fuerte');
INSERT INTO MotivosCita VALUES (19, 'Accidente automovilistico. Golpe en las costillas');
INSERT INTO MotivosCita VALUES (20, 'necesidad urgente de ir al baño muchas veces al día y durante la noch');
INSERT INTO MotivosCita VALUES (21, 'Articulaciones que se inflaman y de color rojo ');
INSERT INTO MotivosCita VALUES (1, 'Visita preanestésica');
INSERT INTO MotivosCita VALUES (2, 'Taquicardia');
INSERT INTO MotivosCita VALUES (3, 'Perdida de cabello excesivo');
INSERT INTO MotivosCita VALUES (4, 'Desórdenes en el peso y síndrome metabólico');
INSERT INTO MotivosCita VALUES (5, 'esofagitis');
INSERT INTO MotivosCita VALUES (6, 'Cirugía general');
INSERT INTO MotivosCita VALUES (7, 'anomalía en la hemoglobina');
INSERT INTO MotivosCita VALUES (8, 'Infecciones recurrentes o graves');
INSERT INTO MotivosCita VALUES (9, 'Piedras o pacientes de Riñón');
INSERT INTO MotivosCita VALUES (10, 'dolor de cabeza repentino y frecuente de forma intensa o punzante');
INSERT INTO MotivosCita VALUES (11, 'Prueba de embarazo');
INSERT INTO MotivosCita VALUES (12, 'Presencia de tejidos');
INSERT INTO MotivosCita VALUES (13, 'Revision anual');
INSERT INTO MotivosCita VALUES (15, 'Sufrio un shock acústico.');
INSERT INTO MotivosCita VALUES (16, 'entrenamiento físico adecuado');
INSERT INTO MotivosCita VALUES (17, 'Acudido varias veces al médico general porque tiene la sensación de que tiene una enfermedad');
INSERT INTO MotivosCita VALUES (18, 'Exposicion constante a quimicos lastimando la respiracion');
INSERT INTO MotivosCita VALUES (19, 'Caida con golpe en muñeca derecha. Inflamacion.');
INSERT INTO MotivosCita VALUES (20, 'Dolor frecuente y/o micción débil.');
INSERT INTO MotivosCita VALUES (21, 'Pérdida de movimiento en las articulaciones');
INSERT INTO MotivosCita VALUES (1, 'Preparación para cirugía');
INSERT INTO MotivosCita VALUES (2, 'Mareos y perdida de conocimiento');
INSERT INTO MotivosCita VALUES (3, 'Irritacion facial');
INSERT INTO MotivosCita VALUES (4, ' enfermo de Sida');
INSERT INTO MotivosCita VALUES (5, 'hemorragia digestiva');
INSERT INTO MotivosCita VALUES (6, 'Cirugía general');
INSERT INTO MotivosCita VALUES (7, 'presencia de glóbulos rojos muy grandes en la sangre');
INSERT INTO MotivosCita VALUES (8, 'déficits de producción de anticuerpos');
INSERT INTO MotivosCita VALUES (9, 'Tensión arterial alta Incontrolada');
INSERT INTO MotivosCita VALUES (10, 'Dificultad para mover cualquier músculo, especialmente si se presenta de forma repentina.');
INSERT INTO MotivosCita VALUES (11, 'Fluidos vaginales extraños');
INSERT INTO MotivosCita VALUES (12, 'Descubrimiento de bolas en la piel');
INSERT INTO MotivosCita VALUES (13, ' irritaciones frecuentes en tus ojos que te hacen sentir comezón y secreciones poco habituales');
INSERT INTO MotivosCita VALUES (15, ' sospecha que ha disminuido la capacidad auditiva');
INSERT INTO MotivosCita VALUES (16, 'dolores musculares persistentes');
INSERT INTO MotivosCita VALUES (17, 'trastorno de déficit de atención e hiperactividad');
INSERT INTO MotivosCita VALUES (18, 'Dolor al respirar');
INSERT INTO MotivosCita VALUES (19, 'Caida sobre el codo');
INSERT INTO MotivosCita VALUES (20, 'dolor en la zona supra púbica.');
INSERT INTO MotivosCita VALUES (21, 'Disminución de la capacidad de mover las articulaciones');
INSERT INTO MotivosCita VALUES (1, 'Administración de anestecia');
INSERT INTO MotivosCita VALUES (2, 'Fatiga ');
INSERT INTO MotivosCita VALUES (3, 'Quemadura');
INSERT INTO MotivosCita VALUES (4, ' insuficiencia suprarrenal');
INSERT INTO MotivosCita VALUES (5, 'Dolor abdominal o tipo cólico');
INSERT INTO MotivosCita VALUES (6, 'Cirugía general');
INSERT INTO MotivosCita VALUES (7, 'carece de hierro');
INSERT INTO MotivosCita VALUES (8, 'déficits parciales de complemento');
INSERT INTO MotivosCita VALUES (9, 'Cánceres de los riñones o del diafragma urinario');
INSERT INTO MotivosCita VALUES (10, 'Rigidez muscular.');
INSERT INTO MotivosCita VALUES (11, 'Dolor al orinar');
INSERT INTO MotivosCita VALUES (12, 'Irritación excesiva el cuerpo');
INSERT INTO MotivosCita VALUES (13, 'cuerpo extraño en los ojos durante un período prolongado');
INSERT INTO MotivosCita VALUES (15, 'Falta de audicion de nacimiento');
INSERT INTO MotivosCita VALUES (16, 'Medidas preventivas');
INSERT INTO MotivosCita VALUES (17, 'Esquizofrenia');
INSERT INTO MotivosCita VALUES (18, 'Asma');
INSERT INTO MotivosCita VALUES (19, 'Golpe en torax');
INSERT INTO MotivosCita VALUES (20, 'Presencia de sangre al orinar.');
INSERT INTO MotivosCita VALUES (21, 'Dolor fibromialgico agravado');
INSERT INTO MotivosCita VALUES (2, 'Problemas de corazon en historial familiar');
INSERT INTO MotivosCita VALUES (3, 'Verrugas');
INSERT INTO MotivosCita VALUES (4, 'hiperplasia adrenal congénita');
INSERT INTO MotivosCita VALUES (5, 'Acidez');
INSERT INTO MotivosCita VALUES (6, 'Cirugía general');
INSERT INTO MotivosCita VALUES (7, 'Defensas bajas');
INSERT INTO MotivosCita VALUES (8, 'Indicación de vacunas profilácticas y terapéuticas.');
INSERT INTO MotivosCita VALUES (9, 'Nefropatía Diabética');
INSERT INTO MotivosCita VALUES (10, 'Temblores en las manos o en cualquier otra zona del cuerpo.');
INSERT INTO MotivosCita VALUES (11, 'Ciclo menstrual irregular');
INSERT INTO MotivosCita VALUES (13, 'Falta de vision');
INSERT INTO MotivosCita VALUES (15, 'Sinusitis');
INSERT INTO MotivosCita VALUES (16, 'ejercicios de movilidad, estiramientos, o masaje para relajar la tensión');
INSERT INTO MotivosCita VALUES (17, 'Euforia constante');
INSERT INTO MotivosCita VALUES (18, 'Tos y falta de aire cronico');
INSERT INTO MotivosCita VALUES (19, 'Golpe en la cabeza con el piso.');
INSERT INTO MotivosCita VALUES (20, 'Infección de orina acompañada de fiebre.');
INSERT INTO MotivosCita VALUES (21, 'Dolor que empeora o más intensa con el aumento de la actividad o el movimiento ');
INSERT INTO MotivosCita VALUES (2, 'Revision general');
INSERT INTO MotivosCita VALUES (3, 'Microdermoabrasion');
INSERT INTO MotivosCita VALUES (4, 'Gigantismo');
INSERT INTO MotivosCita VALUES (5, 'Reflujo');
INSERT INTO MotivosCita VALUES (6, 'Cirugía general');
INSERT INTO MotivosCita VALUES (7, 'Anemia');
INSERT INTO MotivosCita VALUES (8, 'terapia inmunosupresora');
INSERT INTO MotivosCita VALUES (9, 'Necrosis tubular Aguda');
INSERT INTO MotivosCita VALUES (10, 'Problemas para caminar.');
INSERT INTO MotivosCita VALUES (11, 'Metodos anticonceptivos');
INSERT INTO MotivosCita VALUES (13, 'Cansancio en la mirada');
INSERT INTO MotivosCita VALUES (15, 'Cuerpos extraños en oídos');
INSERT INTO MotivosCita VALUES (16, 'Dolor de espalda');
INSERT INTO MotivosCita VALUES (17, 'Delirios diarios');
INSERT INTO MotivosCita VALUES (18, 'Hipertension y falta de respiracion');
INSERT INTO MotivosCita VALUES (19, 'Caida sobre el hombro. Tiene brazo hinchado');
INSERT INTO MotivosCita VALUES (20, 'Presencia de nódulos o bolitas duras en los testículos.');
INSERT INTO MotivosCita VALUES (21, 'Atritis intensificando');
INSERT INTO MotivosCita VALUES (2, 'Sensación de quedarse sin aliento (disnea).');
INSERT INTO MotivosCita VALUES (3, 'Problemas de acne');
INSERT INTO MotivosCita VALUES (4, 'Hipertensión arterial');
INSERT INTO MotivosCita VALUES (5, 'Sensación de llenura (aún sin haber comido)');
INSERT INTO MotivosCita VALUES (6, 'Cirugía general');
INSERT INTO MotivosCita VALUES (7, 'Leucemia ');
INSERT INTO MotivosCita VALUES (8, 'terapia inmunosupresora');
INSERT INTO MotivosCita VALUES (9, 'Tubulo/enfermedades renales intersticiales');
INSERT INTO MotivosCita VALUES (10, 'Movimientos lentos al caminar o realizar cualquier acción');
INSERT INTO MotivosCita VALUES (11, 'Dipositivo DIU');
INSERT INTO MotivosCita VALUES (13, 'Parpados inflamados por dias');
INSERT INTO MotivosCita VALUES (15, 'Alteraciones del Olfato');
INSERT INTO MotivosCita VALUES (16, 'Estres provocando dolor muscular');
INSERT INTO MotivosCita VALUES (17, 'Delirios de celos');
INSERT INTO MotivosCita VALUES (18, 'Falta de aire en persona con sobrepeso');
INSERT INTO MotivosCita VALUES (19, 'Piso mal, pie torcido.');
INSERT INTO MotivosCita VALUES (20, 'Problemas sexuales: eyaculación precoz.');
INSERT INTO MotivosCita VALUES (21, 'Sintomas ligeros de Artritis');
INSERT INTO MotivosCita VALUES (2, 'Dolor en el pecho o taquicardia.');
INSERT INTO MotivosCita VALUES (3, 'lunar que está creciendo evidentemente');
INSERT INTO MotivosCita VALUES (4, 'enanismo');
INSERT INTO MotivosCita VALUES (5, 'Distención abdominal (exceso de gases)');
INSERT INTO MotivosCita VALUES (6, 'Cirugía general');
INSERT INTO MotivosCita VALUES (7, 'Problemas de plaquetas');
INSERT INTO MotivosCita VALUES (8, 'paciente trasplantado');
INSERT INTO MotivosCita VALUES (9, 'Drogas o toxinas que han estropeado el riñón');
INSERT INTO MotivosCita VALUES (10, 'Problemas de equilibrio');
INSERT INTO MotivosCita VALUES (11, 'Irritacion pelvica');
INSERT INTO MotivosCita VALUES (13, 'Conjuntivitis frecuente');
INSERT INTO MotivosCita VALUES (15, 'Obstrucción nasal');
INSERT INTO MotivosCita VALUES (16, 'Preparacion para torneo deportivo');
INSERT INTO MotivosCita VALUES (17, 'Trastornos del sueño.');
INSERT INTO MotivosCita VALUES (18, 'Tabaquismo');
INSERT INTO MotivosCita VALUES (19, 'Se machuco el dedo con la puerta.');
INSERT INTO MotivosCita VALUES (20, 'Problemas sexuales: eyaculación retrógrada.');
INSERT INTO MotivosCita VALUES (21, 'Dolor fuerte en los dedos');
INSERT INTO MotivosCita VALUES (2, ' Dolor de cabeza y fatiga');
INSERT INTO MotivosCita VALUES (3, 'mejillas se enrojecen y se quedan así');
INSERT INTO MotivosCita VALUES (4, 'acromegalia');
INSERT INTO MotivosCita VALUES (5, 'Estreñimiento');
INSERT INTO MotivosCita VALUES (6, 'Cirugía general');
INSERT INTO MotivosCita VALUES (7, 'Problemas de coagulación de sangre');
INSERT INTO MotivosCita VALUES (8, ' infecciones virales crónicas ');
INSERT INTO MotivosCita VALUES (9, 'Enfermedad Renal del vaso sanguíneo');
INSERT INTO MotivosCita VALUES (10, 'Falta de coordinación motriz');
INSERT INTO MotivosCita VALUES (11, 'Colicos frecuentes');
INSERT INTO MotivosCita VALUES (13, 'Secrecion excesiva en lagrimales');
INSERT INTO MotivosCita VALUES (15, 'Rinitis ');
INSERT INTO MotivosCita VALUES (16, 'Mantenimiento');
INSERT INTO MotivosCita VALUES (17, 'Aislamiento social');
INSERT INTO MotivosCita VALUES (18, 'Alergias imposibilitan la respiracion');
INSERT INTO MotivosCita VALUES (19, 'Dolor en la espina dorsal');
INSERT INTO MotivosCita VALUES (20, 'Problemas sexuales: disfunción eréctil.');
INSERT INTO MotivosCita VALUES (21, 'La degeneración del cartílago');
INSERT INTO MotivosCita VALUES (2, 'Sensación de percibir los latidos del corazón  y en ocasiones de forma irregular');
INSERT INTO MotivosCita VALUES (3, 'piel ha cambiado 180 grados de seca a grasa ');
INSERT INTO MotivosCita VALUES (4, 'diabetes insípida');
INSERT INTO MotivosCita VALUES (5, 'Sensación de cuerpo extraño');
INSERT INTO MotivosCita VALUES (6, 'Cirugía general');
INSERT INTO MotivosCita VALUES (7, 'Hemofilia');
INSERT INTO MotivosCita VALUES (8, 'síndromes poliglandulares autoinmunes');
INSERT INTO MotivosCita VALUES (9, 'Daño Hipertenso del nephrosclerosis o del riñón debido a la tensión arterial alta');
INSERT INTO MotivosCita VALUES (10, 'sensación de vértigo');
INSERT INTO MotivosCita VALUES (11, 'Infertilidad');
INSERT INTO MotivosCita VALUES (13, 'Molestia ocular');
INSERT INTO MotivosCita VALUES (15, 'Parálisis Facial');
INSERT INTO MotivosCita VALUES (16, 'Ejercitacion fisica de los musculos');
INSERT INTO MotivosCita VALUES (17, 'Cambios marcados en el estado de ánimo y en el carácter.');
INSERT INTO MotivosCita VALUES (18, 'Falta de respiracion en la noche');
INSERT INTO MotivosCita VALUES (19, 'Golpe fuerte en la nariz');
INSERT INTO MotivosCita VALUES (20, 'Dolor lumbar que se extiende hacia la ingle');
INSERT INTO MotivosCita VALUES (21, 'Sintomas de escoliosis');
INSERT INTO MotivosCita VALUES (1, 'Anestesiología');
INSERT INTO MotivosCita VALUES (2, 'Cansancio, sensación de ahogo, hinchazón de los tobillos,');
INSERT INTO MotivosCita VALUES (3, 'Resequedad excesiva en zonas del cutis');
INSERT INTO MotivosCita VALUES (4, 'hipertiroidismo ');
INSERT INTO MotivosCita VALUES (5, 'hemorroides');
INSERT INTO MotivosCita VALUES (6, 'Cirugía general');
INSERT INTO MotivosCita VALUES (7, 'Mieloma');
INSERT INTO MotivosCita VALUES (8, 'abortos espontáneos de repetición con factor inmunológico.');
INSERT INTO MotivosCita VALUES (9, 'Enfermedad de riñón ');
INSERT INTO MotivosCita VALUES (10, 'Dificultad para moverse de forma normal');
INSERT INTO MotivosCita VALUES (11, 'Planeacion familiar');
INSERT INTO MotivosCita VALUES (13, 'Dolor o punzadas en la vista ');
INSERT INTO MotivosCita VALUES (15, 'Resulta difícil escuchar o mantener una conversación en ambientes ruidosos. ');
INSERT INTO MotivosCita VALUES (16, 'Lesiones musculares deportivas');
INSERT INTO MotivosCita VALUES (17, 'Alucinaciones');
INSERT INTO MotivosCita VALUES (18, 'Ronquidos muy fuertes');
INSERT INTO MotivosCita VALUES (19, 'Caida de bicicleta, rodilla hinchada');
INSERT INTO MotivosCita VALUES (20, 'Esterilidad e infertilidad');
INSERT INTO MotivosCita VALUES (21, 'Fatiga cronica');
INSERT INTO MotivosCita VALUES (2, ' impotencia sexual ');
INSERT INTO MotivosCita VALUES (3, 'Varices');
INSERT INTO MotivosCita VALUES (4, 'paratiroides ');
INSERT INTO MotivosCita VALUES (5, 'Ictericia ');
INSERT INTO MotivosCita VALUES (6, 'Cirugía general');
INSERT INTO MotivosCita VALUES (7, 'Trastornos hemorrágicos');
INSERT INTO MotivosCita VALUES (8, 'Uveítis');
INSERT INTO MotivosCita VALUES (9, 'La insuficiencia renal Aguda o la baja súbita del riñón funciona');
INSERT INTO MotivosCita VALUES (10, 'Falla de memoria');
INSERT INTO MotivosCita VALUES (11, 'Aborto');
INSERT INTO MotivosCita VALUES (12, 'Tratamiento de quimioterapia');
INSERT INTO MotivosCita VALUES (13, 'desorientación visual ');
INSERT INTO MotivosCita VALUES (15, 'Necesita ver la televisión o escuchar música con el volumen más alto que el resto de la familia.');
INSERT INTO MotivosCita VALUES (16, 'lesiones musculares proceso de recuperación de cirugia');
INSERT INTO MotivosCita VALUES (17, 'Una emoción negativa que dura más de lo normal.');
INSERT INTO MotivosCita VALUES (18, 'Tos con sangrado');
INSERT INTO MotivosCita VALUES (19, 'Golpe en la frente');
INSERT INTO MotivosCita VALUES (20, 'Pérdida involuntaria de la orina.');
INSERT INTO MotivosCita VALUES (21, 'Contracciones musculares en la espalda');
INSERT INTO MotivosCita VALUES (2, 'Dolor en el pecho');
INSERT INTO MotivosCita VALUES (3, 'Manchas faciales');
INSERT INTO MotivosCita VALUES (4, ' déficit de hormona de crecimiento en el adulto');
INSERT INTO MotivosCita VALUES (5, 'Gastritis');
INSERT INTO MotivosCita VALUES (6, 'Cirugía general');
INSERT INTO MotivosCita VALUES (7, 'Trasplante de células madre/médula ósea ');
INSERT INTO MotivosCita VALUES (8, 'Trasplante de Órganos');
INSERT INTO MotivosCita VALUES (9, 'Presencia de sangre, proteínas o moldes y cristales en la orina');
INSERT INTO MotivosCita VALUES (10, 'Dolor de cabeza intensificado');
INSERT INTO MotivosCita VALUES (11, 'Revision contra enfermedades venereas');
INSERT INTO MotivosCita VALUES (13, 'Visita de rutina');
INSERT INTO MotivosCita VALUES (15, 'Dificultad para escuchar o comprender una conversación');
INSERT INTO MotivosCita VALUES (16, 'lesiones musculares producto de alguna intervención quirúrgica');
INSERT INTO MotivosCita VALUES (17, 'Ansiedad excesiva causa conflicto con vida normal');
INSERT INTO MotivosCita VALUES (18, 'Tos con flemas muy abundante');
INSERT INTO MotivosCita VALUES (19, 'Golpe en cadera');
INSERT INTO MotivosCita VALUES (20, 'Molestias urinarias');
INSERT INTO MotivosCita VALUES (21, 'Dolor persistente e inflamación de las articulaciones que duran más de dos semanas');